version: '3.7'

services:
  app:
    build:
      context: .
    expose:
      - "5001"
    restart: always
    environment:
      - VIRTUAL_HOST=hailrake.space

  proxy:
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - app
